import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <h1>Simple App ver 2.0</h1>
        <hr />
          <Link href="/">Home</Link>&nbsp;&nbsp;&nbsp;&nbsp;
          <Link href="/feedback">Feedback</Link>&nbsp;&nbsp;&nbsp;&nbsp;
          <Link href="/users">Users</Link>
        <hr />
        {children} 
       
      </body>
    </html>
  )
}
